name: Auto Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  main:
    name: Auto Deploy to AWS
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.KEY }}
          run: |
            cd /home/backend_nestjs
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
