name: Auto Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  main:
    name: Auto Deploy to AWS
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /home/backend_nestjs
            cd /home/backend_nestjs
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
